### PR TITLE
[FEATURE] scheduler handler to call to twitter api v2

### PR DESCRIPTION
**Pull request by Shubham8287**
PR to fix TwitterSchedulerHandler to post tweets on twitter.

#97 
/claim #97

### CODE REVIEW

**Comment by Shubham8287** [comment]
I tested twiiter Post specific changes locally and verified that the Twitter API integration is working. However, I didn't have the "lastTwittedJobID" field in my local database, so I couldn't test that part. The job-related code is similar to the Telegram integration and hasn't been modified by me.

You can follow these steps to generate your own access tokens: https://developer.twitter.com/en/docs/authentication/oauth-1-0a.

Please review my changes and let me know if you have any feedback.

**Comment by dm161** [comment]
unfortunately this is the old API / endpoint

please follow the new API docs
- https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/overview
- Create tweet https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-update
- The new api takes api_key, secret and bearer token not the old 4 keys

**Comment by Shubham8287** [comment]
@dm161, I am using v2 API in my PR, isn't that already the latest? The link you mentioned belongs to v1.1, aren't they supposed to be the older one? Can you clarify please.

**Comment by dm161** [comment]
@Shubham8287 ok my apologies I was confused because the new api accepts api key, secret and bearer token, but the old api accepts the old 4 keys, client key, client secret, acess token, access token secret, did you manage to run a test even with curl on the new api? how many keys do you use? 3 or 4?

**Comment by Shubham8287** [comment]
@dm161 yes, I am able to hit using curl as well as by running our code. (I commented out the job fetching related stuff and mocked the tweet string). I am able to post tweets using it.

**Comment by Shubham8287** [comment]
Can you share where you read about 3 keys, maybe that's just a different auth method. The one I am using is oauth1, twitter API also supports auth2, I am making a guess maybe oauth2 authenticates that way but I think both are valid as I followed the official doc to authenticate - https://developer.twitter.com/en/docs/authentication/oauth-1-0a. Even the reference you shared in the issue https://developer.twitter.com/en/docs/twitter-api/tweets/manage-tweets/quick-start in issue uses the same oauth1 method.

**Comment by dm161** [comment]
@Shubham8287 reviewing again this now

**Comment by Shubham8287** [comment]
@dm161  how did the review go? I am wondering if it still takes you more time to review, should I resume working linkedin task?

**Comment by dm161** [comment]
@Shubham8287 reviewing this now will respond in a couple of hours

**Comment by dm161** [comment]
@Shubham8287 tested and it returns 401, I have assigned $100 to this task because I expect you to spend some time generating keys on twitter creating a test app and trying the whole flow. Please add screenshots when you have done the following steps.

**Comment by dm161** [comment]
thats how i generate consumer key+secret 
image

**Comment by dm161** [comment]
and thats where i generate access token+access token secret 
image

**Comment by Shubham8287** [comment]
> @Shubham8287 tested and it returns 401, I have assigned $100 to this task because I expect you to spend some time generating keys on twitter creating a test app and trying the whole flow. Please add screenshots when you have done the following steps.

@dm161, I raised the PR after spending enough time to find best auth way as well as testing it well - https://github.com/golang-cafe/job-board/pull/103#issuecomment-1519090328. Attaching screenshots for same.
image
image
image

I generated tokens in same way as you. in env file, I am mapping `Consumer` key and secret to `Client` key and secret, I hope you are doing the same.

**Comment by dm161** [comment]
thank you - did you try also running through local env? it could be that the oauth client is not configured correctly. I will also try to run the postman requesst

**Comment by Shubham8287** [comment]
@dm161  you see, the 2nd screenshot is from job-board server.
also, there was small issue in my PR related to escaping endline in serialized json body. Fixed that, I think that was causing it to fail for you and if you tried curl or Postman to get 401, its litte tricky to setup oauth there. You can refer to my ss to try with Postman or e2e testing should also work now as I tested that.

**Comment by Shubham8287** [comment]
@dm161 Were you able to successfully test it? Also, mock job that we use for local run have expired `SocialMediaEligibilityExpiredAt`, you may like to comment the check condition to test it.

**Comment by dm161** [comment]
I had to review other Prs, but I will try again generating new tokens and trying this out - unfortunately it takes time for me to generate tokens and test locally to make sure it's working - will update you as soon as i have done this in the next day or two

**Comment by Shubham8287** [comment]
@dm161 did you get any time to review it? I will be on vacation from next weeks so hoping to close this soon.

**Comment by dm161** [comment]
Still didn’t manage to run it locally as it returns errors.

**Comment by Shubham8287** [comment]
Can you please write the steps you are following to run it locally? And
what error are you getting?

**Comment by ghost** [comment]
all dev work is currently frozen/on-hold. I will reopen PR as soon as this changes

**Pull request closed without merging**
